# Site settings
title: Nerderrhein
email: hallo@nerderrhein.de
description: > # this means to ignore newlines until "baseurl:"
  Der Nerderrhein ist ein IRC Channel auf freenode.net wo sich Nerds aus der Region in und um den Niederrhein treffen.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nerderrhein.de" # the base hostname & protocol for your site
twitter_username: nerderrhein
github_username:  nerderrhein

#Exclude things
exclude: [Gemfile, Gemfile.lock, CNAME, LICENSE, README.md]

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Add plugins
gems:
   - jekyll-sitemap
   - jekyll-mentions
